/**
 * 项目常量定义
 * 用于替换代码中的魔法数字，提高代码可读性和可维护性
 */

// AI 相关常量
export const AI_CONSTANTS = {
  // Token 相关
  DEFAULT_CONTEXT_WINDOW: 8192,
  DEFAULT_OUTPUT_RESERVE_TOKENS: 512,
  DEFAULT_MAX_RESPONSE_TOKENS: 2000,
  DEFAULT_MAX_REQUEST_TOKENS: 8000,
  MIN_DYNAMIC_BUDGET: 256,
  MAX_DYNAMIC_BUDGET: 8192,
  MAX_RESPONSE_TOKENS_LIMIT: 8192,
  
  // 字符到Token的估算比例
  CHARS_PER_TOKEN: 4,
  
  // 重试相关
  DEFAULT_REQUEST_RETRIES: 3,
  DEFAULT_REQUEST_BACKOFF_MS: 500,
  
  // 文件大小限制
  DEFAULT_MAX_FILE_SIZE_KB: 100,
  
  // 确认文本长度限制
  MAX_CONFIRMATION_TEXT_LENGTH: 100
};

// 分段分析相关常量
export const SEGMENTATION_CONSTANTS = {
  // 每段最大行数
  DEFAULT_MAX_LINES_PER_SEGMENT: 100,
  
  // 上下文重叠行数
  DEFAULT_CONTEXT_OVERLAP_LINES: 5,
  
  // 每段最大Token数
  DEFAULT_MAX_TOKENS_PER_SEGMENT: 3000,
  
  // Token估算比例
  DEFAULT_TOKEN_RATIO: 4,
  
  // 摘要最大长度
  DEFAULT_MAX_SUMMARY_LENGTH: 500
};

// 文件权限相关常量
export const FILE_PERMISSIONS = {
  EXECUTABLE: '755'
};

// 批处理相关常量
export const BATCH_CONSTANTS = {
  DEFAULT_MAX_REQUEST_TOKENS: 4000,
  TOKEN_RATIO: 4,
  CHUNK_OVERLAP_LINES: 5,
  MIN_FILES_PER_BATCH: 3,
  MAX_FILES_PER_BATCH: 50,
  UTILIZATION_THRESHOLD: 0.9,
  BUFFER_SIZE: 100,
  SNIPPET_LENGTH: 1000,
  CHINESE_CHAR_MULTIPLIER: 1.5,
  CODE_STRUCTURE_BONUS: 0.1,
  
  // 利用率计算相关
  UTILIZATION_PERCENTAGE_MULTIPLIER: 100,
  VALUE_CALCULATION_MULTIPLIER: 1000,
  
  // 缓冲区大小
  MAX_BUFFER_SIZE: 10 * 1024 * 1024, // 10MB
  
  // 代码片段长度限制
  MAX_SNIPPET_LENGTH: 100,
  MAX_SNIPPET_PART_LENGTH: 200,
  
  // 对象池大小限制
  MAX_BATCH_POOL_SIZE: 20,
  MAX_ITEM_POOL_SIZE: 100,
  MAX_CHUNK_POOL_SIZE: 50,
  MAX_STATS_POOL_SIZE: 20,
  
  // 对象池初始化大小
  INITIAL_BATCH_POOL_SIZE: 10,
  INITIAL_ITEM_POOL_SIZE: 50,
  INITIAL_CHUNK_POOL_SIZE: 20,
  INITIAL_STATS_POOL_SIZE: 10,
  
  // 缓存大小限制
  MAX_TOKEN_CACHE_SIZE: 1000,
  MAX_REGEX_CACHE_SIZE: 1000,
  MAX_COMMENT_RANGE_CACHE_SIZE: 500,
  MAX_DISABLE_RANGE_CACHE_SIZE: 500,
  
  // 循环限制
  MAX_DIRECTORY_SEARCH_DEPTH: 20,
  
  // 文件大小相关
  FILE_SIZE_KB_THRESHOLD: 1024, // 1MB
  CACHE_KEY_PREFIX_LENGTH: 100
};

// HTTP 状态码相关常量
export const HTTP_STATUS = {
  TOO_MANY_REQUESTS: 429,
  SERVER_ERROR_START: 500,
  SERVER_ERROR_END: 600
};

// 默认配置值
export const DEFAULT_CONFIG = {
  MAX_RESPONSE_TOKENS: 4096,
  MAX_FILE_SIZE_KB: 100,
  MAX_REQUEST_TOKENS: 8000,
  TEMPERATURE: 0.1
};